// <auto-generated/>
global using Microsoft.Extensions.DependencyInjection;
global using Test.Cloud.Common.DTOs.Responses;
global using Test.Cloud.Model.Entities.Common;
global using Test.Cloud.Services.Tests;
global using Test.Cloud.Facade.Tests;
global using Test.Cloud.Facade.Tests.Impl;
global using Test.Cloud.Services.Phrases;
global using Test.Cloud.Facade.Phrases;