// <auto-generated/>
global using Test.Cloud.Persistence.Context;
global using Test.Cloud.Persistence.DAO.Tests;
global using Test.Cloud.Persistence.DAO.Tests.Impl;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
