// <auto-generated/>
global using Test.Cloud.Api;
global using Test.Cloud.Facade;
global using Test.Cloud.Persistence;
global using Test.Cloud.Services;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Serilog.Events;
global using StackExchange.Redis;
global using Steeltoe.Extensions.Configuration.Placeholder;